# Generated by Django 5.0.3 on 2026-03-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado')], default='aberto', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advogado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='processos/documentos/')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('advogado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='processos.processo')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
