# Generated by Django 5.0.3 on 2026-03-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='processos/documentos/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.historicoprocesso')),
            ],
        ),
    ]
